### ISSUE TITLE
Software or tool used for the firmware

### ISSUE THREAD

**Issue by TinManAkshay** [themainframe/thermal-camera#2]
Hi,

I saw got Lepton 3 working on ESP32. How did you program the code into the ESP32? Was it a Linux system? Can you give some information on that. I'd appreciate that.

Also, what is the max frame rate you could get from this firmware model?

Thanks,
Akshay

**Comment by themainframe** [comment]
This project uses the [ESP-IDF](https://github.com/espressif/esp-idf) toolchain to build & flash onto ESP32 hardware, so that'd be a good place to start =)

As for maximum framerate - really difficult to say I'm afraid. I expect it achieves close to if not above the 9Hz update rate of the Lepton though.
